### ISSUE TITLE
Missing chapters / broken links

### ISSUE THREAD

**Issue by liz-is** [LTLA/csawBook#1]
Hi, The links for chapter 4, 5, and 6 in the sidebar of the book page are broken, appearing as e.g. "chap:filter.html" instead of e.g. "http://bioconductor.org/books/3.15/csawBook/more-counting-options.html". Manually going to "http://bioconductor.org/books/3.15/csawBook/filter.html" returns "page not found".

**Comment by LTLA** [comment]
Thanks - looks like 216b72b7d2b4fca28024f5301391a02472206ed6 never made it to BioC. Should be fixed hopefully.

**Comment by liz-is** [comment]
Hm, I still see the same behaviour. How often / when do the books get rebuilt on Bioc's servers? I can check again in a few days

**Comment by LTLA** [comment]
Weekly, I guess. Still says 1.4.0 on https://bioconductor.org/books/3.15/csawBook/.

**Comment by liz-is** [comment]
Now it's 1.4.1 and the links are correct :)
